dataset_name: 'gsm8k'
model_path: "/lus/lfs1aip2/projects/public/u6er/mingyu/models/LLaDA-8B-Instruct"
data_root: "/lus/lfs1aip2/projects/public/u6er/mingyu/WINO-DLLM/LLaDA/data"
# model_path: "/mnt/fast/nobackup/scratch4weeks/mc03002/models/LLaDA-8B-Instruct"
# data_root: "/mnt/fast/nobackup/scratch4weeks/mc03002/WINO-DLLM/LLaDA/data"

dataset_config:
  data_loader: 'huggingface' # can be chosen from [huggingface, custom_loader]
  loader_fn: null
  load_dataset_args: { path: "gsm8k", name: "main" }
  split: "test"
  doc_to_text_fn: "gsm8k_doc_to_text"
  extract_answer_fn: "gsm8k_extract_answer"
  is_correct_fn: "gsm8k_is_correct"
  eval_mode: "binary"
  prompt_suffix: "<reasoning>"

generation_args:
  gen_length: 256
  block_length: 32
  temperature: 0.0
  steps: 256

method: 'soar' #default
method_args:
  wino:
    threshold: 0.6
    threshold_back: 0.9